//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.CoreLibrary
{
    using System;
    using System.Data.Entity;
    
    public partial class BookStoreEntities : DbContext
    {
        public BookStoreEntities()
            : base("name=BookStoreEntities")
        {
    		this.Initialize();
        }
    
    	#region DbSets
        public virtual DbSet<Book> Books { get; set; }
    	#endregion
    
    	partial void Initialize();
    }
}
